rvm:
  - 3.0.0

gemfile:
  - gemfiles/Gemfile.6.0.pg
  - gemfiles/Gemfile.6.1.pg
  - gemfiles/Gemfile.7.0.pg

  - gemfiles/Gemfile.6.0.mysql
  - gemfiles/Gemfile.6.1.mysql
  - gemfiles/Gemfile.7.0.mysql
